[build]
  publish="build"
  command = "CI= npm run build"

[[redirects]]
  from = "https://main--fluffy-travesseiro-9155aa.netlify.app/Search/paper/*"
  to = "https://serpapi.com/:splat"
  status = 200